#!/usr/bin/with-contenv sh

# rocker/ uses S6 to manage container initialization. We'll copy this
# file to /etc/cont-init.d to place REDIS environment variables in the
# environment seen in Rstudio server

cat <<EOF >> /usr/local/lib/R/etc/Renviron
REDIS_SERVICE_HOST="$REDIS_SERVICE_HOST"
REDIS_SERVICE_PORT="$REDIS_SERVICE_PORT"
EOF
